apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../base
patches:
  - target:
      group: clusters.nkp.nutanix.com
      version: v1alpha1
      kind: NKPCluster
      name: cluster-template
    patch: |-
      - {op: replace, path: /metadata/name, value: nkp-wlc-b}
      - {op: replace, path: /metadata/namespace, value: nkp-flux-provisioned-phvwv-jjxpb}
      - {op: replace, path: /metadata/labels/konvoy.d2iq.io~1cluster-name, value: nkp-wlc-b}
      - {op: replace, path: /spec/capiCluster/topology/variables/0/value/addons/ccm/credentials/secretRef/name, value: nkp-wlc-b-pc-credentials}
      - {op: replace, path: /spec/capiCluster/topology/variables/0/value/addons/csi/providers/nutanix/credentials/secretRef/name, value: nkp-wlc-b-pc-credentials-for-csi}
      - {op: replace, path: /spec/capiCluster/topology/variables/0/value/addons/csi/providers/nutanix/storageClassConfigs/volume/parameters/description, value: CSI StorageClass nutanix-volume for nkp-wlc-b}
      - {op: replace, path: /spec/capiCluster/topology/variables/0/value/addons/csi/providers/nutanix/storageClassConfigs/volume/volumeBindingMode, value: Immediate}
      - {op: replace, path: /spec/capiCluster/topology/variables/0/value/addons/konnectorAgent/credentials/secretRef/name, value: nkp-wlc-b-pc-credentials-for-konnector-agent}
      - {op: replace, path: /spec/capiCluster/topology/variables/0/value/addons/serviceLoadBalancer/configuration/addressRanges/0/start, value: "${IP_START}.147"}
      - {op: replace, path: /spec/capiCluster/topology/variables/0/value/addons/serviceLoadBalancer/configuration/addressRanges/0/end, value: "${IP_START}.149"}
      - {op: add, path: /spec/capiCluster/topology/variables/0/value/addons/serviceLoadBalancer/configuration/addressRanges/1, value: {start: "${IP_START}.152", end: "${IP_START}.152"}}
      - {op: replace, path: /spec/capiCluster/topology/variables/0/value/nutanix/controlPlaneEndpoint/host, value: "${IP_START}.146"}
      - {op: replace, path: /spec/capiCluster/topology/variables/0/value/nutanix/prismCentralEndpoint/credentials/secretRef/name, value: nkp-wlc-b-pc-credentials}
      - {op: replace, path: /spec/capiCluster/topology/workers/machineDeployments/0/variables/overrides/0/value/nutanix/machineDetails/subnets/0/name, value: secondary}
      - {op: add, path: /spec/capiCluster/topology/variables/0/value/globalImageRegistryMirror, value: {credentials: {secretRef: {name: harbor-registry-credentials}}, url: "https://${IP_START}.51:5000/nkpbundle"}}
      - {op: add, path: /spec/capiCluster/topology/variables/0/value/imageRegistries, value: [{credentials: {secretRef: {name: harbor-registry-credentials}}, url: "https://${IP_START}.51:5000"}]}
