apiVersion: clusters.nkp.nutanix.com/v1alpha1
kind: NKPCluster
metadata:
  annotations:
    clusters.nkp.nutanix.com/adopted-capi-cluster: ""
    clusters.nkp.nutanix.com/adopted-kommander-cluster: ""
  finalizers:
  - clusters.nkp.nutanix.com/capicluster-cleanup
  - clusters.nkp.nutanix.com/kommandercluster-cleanup
  labels:
    cluster.x-k8s.io/cluster-name: nkp-wlc-b
    cluster.x-k8s.io/provider: nutanix
    konvoy.d2iq.io/cluster-name: nkp-wlc-b
    konvoy.d2iq.io/provider: nutanix
    kustomize.toolkit.fluxcd.io/name: nkp-flux-provisioned
    kustomize.toolkit.fluxcd.io/namespace: nkp-flux-provisioned-phvwv-jjxpb
    topology.cluster.x-k8s.io/owned: ""
    workspaces.kommander.mesosphere.io/workspace-ref: 5186c6ec-c416-4950-bc39-8416c1507af0
  name: nkp-wlc-b
  namespace: nkp-flux-provisioned-phvwv-jjxpb
spec:
  capiCluster:
    clusterNetwork:
      pods:
        cidrBlocks:
        - 192.168.0.0/16
      services:
        cidrBlocks:
        - 10.96.0.0/12
    topology:
      classRef:
        name: nkp-nutanix-v2.18.0
      controlPlane:
        replicas: 3
      variables:
      - name: clusterConfig
        value:
          addons:
            ccm:
              credentials:
                secretRef:
                  name: nkp-wlc-b-pc-credentials
              strategy: HelmAddon
            clusterAutoscaler:
              strategy: HelmAddon
            cni:
              provider: Cilium
              strategy: HelmAddon
            cosi:
              strategy: HelmAddon
            csi:
              defaultStorage:
                provider: nutanix
                storageClassConfig: volume
              providers:
                nutanix:
                  credentials:
                    secretRef:
                      name: nkp-wlc-b-pc-credentials-for-csi
                  storageClassConfigs:
                    volume:
                      allowExpansion: true
                      parameters:
                        csi.storage.k8s.io/fstype: ext4
                        description: CSI StorageClass nutanix-volume for nkp-wlc-b
                        flashMode: DISABLED
                        hypervisorAttached: ENABLED
                        storageContainer: default
                        storageType: NutanixVolumes
                      reclaimPolicy: Delete
                      volumeBindingMode: Immediate
                  strategy: HelmAddon
              snapshotController:
                strategy: HelmAddon
            konnectorAgent:
              credentials:
                secretRef:
                  name: nkp-wlc-b-pc-credentials-for-konnector-agent
              enableKubeconfigUpload: true
            nfd:
              strategy: HelmAddon
            serviceLoadBalancer:
              configuration:
                addressRanges:
                - end: 10.38.48.149
                  start: 10.38.48.147
              provider: MetalLB
          controlPlane:
            autoRenewCertificates:
              daysBeforeExpiry: 180
            nodeRegistration:
              ignorePreflightErrors:
              - SystemVerification
            nutanix:
              machineDetails:
                bootType: uefi
                cluster:
                  name: SA-GPU
                  type: name
                image:
                  name: nkp-ubuntu-24.04-release-cis-1.35.2-20260626141256.qcow2
                  type: name
                memorySize: 16Gi
                subnets:
                - name: secondary
                  type: name
                systemDiskSize: 80Gi
                vcpuSockets: 4
                vcpusPerSocket: 1
          dns:
            coreDNS: {}
          encryptionAtRest:
            providers:
            - secretbox: {}
          globalImageRegistryMirror:
            credentials:
              secretRef:
                name: harbor-registry-credentials
            url: https://10.38.48.51:5000/nkpbundle
          imageRegistries:
          - credentials:
              secretRef:
                name: harbor-registry-credentials
            url: https://10.38.48.51:5000
          kubeProxy:
            mode: disabled
          nutanix:
            controlPlaneEndpoint:
              host: 10.38.48.146
              port: 6443
              virtualIP:
                provider: KubeVIP
            prismCentralEndpoint:
              credentials:
                secretRef:
                  name: nkp-wlc-b-pc-credentials
              insecure: true
              url: https://10.38.48.7:9440
          users:
          - name: konvoy
            sshAuthorizedKeys:
            - |
              ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCwZ7cWgwxvq/AYU3eSBqRwXpKL5ch9egNE31HBdt+Jtl/SRFHR2tv6e8Z4jy8EHy6D9JobNZg2iPEVrV8R+po6KYGMDggpJuAV9fgPbXo0L4fwct62TYLHnB7iXjbBUsjR2foWI58C8zY3ee+fdYEjEoz7pP8DwqHo4RUvUATxAjTMraWxq2n2NksUoHrwM9DboRh8TDKRogQtu8esPjfvRqds6U4VQfY+LfPPsbb/30nZKEFGedwr1lEjHxMEI7oTbW5etF1o+apWzXTH4ZKDLStZrR6OIyqADRm1I0zpW9O3Z0X8VUH1GvmBGHwiUXPzytfa3+xPDeQ3p1vXCecCd5MclufxP/W+reisNwTOY+GN3VVq0sTZnZFrEDl/yy9r+fvPLbRGSGCEP2CK+UlWpWcATi+MQNKWekHMQiI2BX0CUWKTr45BnKOj3b5GucNF6bLFchuPC8enzRfT6mbKEX2azv0rCK76Q3buJklrwexHwkfCBoYcs15aUkfTPac=
            sudo: ALL=(ALL) NOPASSWD:ALL
      version: v1.35.2
      workers:
        machineDeployments:
        - class: default-worker
          metadata:
            annotations:
              cluster.x-k8s.io/cluster-api-autoscaler-node-group-max-size: "4"
              cluster.x-k8s.io/cluster-api-autoscaler-node-group-min-size: "8"
          name: md-0
          variables:
            overrides:
            - name: workerConfig
              value:
                nodeRegistration:
                  ignorePreflightErrors:
                  - SystemVerification
                nutanix:
                  machineDetails:
                    bootType: uefi
                    cluster:
                      name: SA-GPU
                      type: name
                    image:
                      name: nkp-ubuntu-24.04-release-cis-1.35.2-20260626141256.qcow2
                      type: name
                    memorySize: 32Gi
                    subnets:
                    - name: secondary
                      type: name
                    systemDiskSize: 80Gi
                    vcpuSockets: 16
                    vcpusPerSocket: 1
  capiClusterRef:
    name: nkp-wlc-b
    namespace: nkp-flux-provisioned-phvwv-jjxpb
  kommanderCluster:
    labels:
      cluster.x-k8s.io/cluster-name: nkp-wlc-b
      cluster.x-k8s.io/provider: nutanix
      kustomize.toolkit.fluxcd.io/name: nkp-flux-provisioned
      kustomize.toolkit.fluxcd.io/namespace: nkp-flux-provisioned-phvwv-jjxpb
      topology.cluster.x-k8s.io/owned: ""
    spec:
      clusterRef:
        capiCluster:
          name: nkp-wlc-b
          namespace: nkp-flux-provisioned-phvwv-jjxpb
      kubeconfigRef:
        name: nkp-wlc-b-kubeconfig
      namespaceRef:
        name: nkp-flux-provisioned-phvwv-jjxpb
      ociRegistry:
        certSecretRef:
          name: nkp-wlc-b-oci-cert
        mirrorURL: https://10.38.48.51:5000/nkpbundle
        secretRef:
          name: nkp-wlc-b-oci-creds
      platform:
        version: v2.18.0
  kommanderClusterRef:
    name: nkp-wlc-b
    namespace: nkp-flux-provisioned-phvwv-jjxpb
  version: v2.18.0
